# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viUDfn9oE2Ej-DYs7lNfqr0JU-7FyHsz
"""

import pandas as pd
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')

# Loading the dataset
df = pd.read_csv('Airlines(1).csv')

df.head()

# Gettig the shape of features
df.shape

# All the info about dataset
df.info()

# Getting all the stats from the dataset
df.describe()

# Dropping unnecessary columns
cleaned_df = df.drop('ID#',axis = 1)# ID is a unique id that is given to each passenger which does not has any information and hence dropped.
cleaned_df.head()

# Scaling all the features to bring all the values of the features into a same range or scale
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_df = scaler.fit_transform(cleaned_df)
scaled_df
df = pd.DataFrame(scaled_df,columns = cleaned_df.columns)
df.head()

# visualizations
from matplotlib import pyplot as plt
import seaborn as sns
print("\nDisplaying feature distributions...")
df.hist(bins=20, figsize=(20, 15))
plt.show()

# Observing outliers using the boxplot
print("\nDisplaying box plots to identify outliers...")
plt.figure(figsize=(20, 10))
sns.boxplot(data=df)
plt.title('Box Plots of Features')
plt.xticks(rotation=90)
plt.show()

# K - Means clustering
from sklearn.cluster import KMeans
inertia_values = []
k_range = range(1,11)
for k in k_range:
    kmeans = KMeans(n_clusters = k,random_state = 42)
    kmeans.fit(df)
    inertia_values.append(kmeans.inertia_)

# Plotting the elbow curve for optimal K
plt.figure(figsize = (10,6))
plt.plot(k_range,inertia_values,marker = 'o',linestyle= '--')
plt.title('Elbow curve')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia_values')
plt.xticks(k_range)
plt.grid(True)
plt.show()

# From Elbow curve 4 is the optimal number of cluster required for this analysis
Optimal_k = 4
# Applying optimal_k onto the kmeans clustering
kmeans = KMeans(n_clusters = Optimal_k,random_state = 42)
k_cluster=kmeans.fit_predict(df)
df['k_cluster'] = k_cluster # cluster variable contains all the cluster values from 1 to 10 it shows which passenger lies in which cluster
from sklearn.metrics import silhouette_score
silhouette_score = silhouette_score(df, k_cluster)
print(f'for k = {Optimal_k} the silhouette score is {silhouette_score}')
df.head()

"""Silhouette score: It is a score that tells whether the data points are perfectly assigned  to the clusters
>0.5 is a strong cluster arrangement which data points are well arranged in the clusters.
<0.5 is a weak cluster arrangement
silhouette score = '0' or near to '0' means the clusters will overlap eachother.
for k = 4 the silhouette score is 0.27604149683953577 here the clusters are overlapped in this case if the no of clusters are increased that is at k=10 the score is 0.45 which is better than the score of k=4. Here Elbow curve said that k=4  is the correct no of cluisters and silhouette score tells that increase the number of clusters so that clusters are separated very well. Here we might think to increase the number of clusters but if no of clusters selected are 10 then the plot becomes messy the results cannot be interpreted and data is not uderstood well. So that is the reason Elbow curve is the best choice to obtain optimal k

"""

import scipy
import scipy.cluster.hierarchy as sch # To Build a dendogram
from sklearn.cluster import AgglomerativeClustering

print("Creating a dendrogram to check the no of clusters needed")
plt.figure(figsize = (20,10))
dendogram = sch.dendrogram(sch.linkage(df,method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('Passengers')
plt.ylabel('Euclidean distance')
plt.show()

# Dendrogram suggest 2 clusters
n_clusters = 2
hierarchy_cluster = AgglomerativeClustering(n_clusters = n_clusters,linkage = 'ward')
hierarchy_cluster.fit_predict(df)
df['hierarchy_cluster'] = hierarchy_cluster.labels_ # Storing the clusters obtained from the AgglomerativeClustering into the dataframe
print(f"Done Applying Agglomerative clustering with {n_clusters} clusters")
df.head()

from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Selecting the Minpoints
# Minpoints are calculated using 2 * total_no_of_features
min_samples = 22 # As in our dataset there are 11 features
neighbors = NearestNeighbors(n_neighbors = min_samples) # Nearest neighbour is a tool used to find the nearest neighbors from a data point within the epsilon
neighbors_fit = neighbors.fit(df)
distances,indices = neighbors_fit.kneighbors(df) # here i am finding the k neighbors that is 22 neighbors with respect to the data point and getting distance and indices
distances = np.sort(distances[:, min_samples-1],axis = 0) #here from distance table i am getting all the 22nd neighbors distance of each data point
# Plotting the Epsilon
plt.figure(figsize = (10,6))
plt.plot(distances)
plt.title('Epsion plot')
plt.xlabel('Data points')
plt.ylabel('Distance')
plt.grid(True)
plt.show()

# From  the epsion plot 1.8 is the value where there is a curve(elbow).Hence 2.5 is the best epsilon value
epsilon = 1.8
min_samples = 22
dbscan = DBSCAN(eps = 1.8,min_samples = min_samples)
cluster_dbscan = dbscan.fit_predict(df)
# Sihouette score will only work only when there are two or more clusters so hence implementing if and else block to check whether DBSCAN has more than one cluster
from sklearn.metrics import silhouette_score
if len(set(cluster_dbscan)  - {-1}) > 1: # set will give unique values and not selecting -1 which are noise points >1 answers the question of whether are more than one cluster
  score_dbscan = silhouette_score(df[cluster_dbscan != -1],cluster_dbscan[cluster_dbscan !=-1])#here i am matching the dataframe and the labels in the cluster_dbscan col
  print(f'For epsilon value of {epsilon} and {min_samples} min_samples the silhouette score is {score_dbscan:.4f}')
else:
  print('There are no clusters more than one in DBCSAN Algorithm')

# Storing the labels of clusters obtained using DBSCAN Algorithm
df['cluster_dbscan'] = cluster_dbscan

df['cluster_dbscan'].value_counts()

"""0.31 is a good sihouette score that means clusters are little overlapped but not too much.
+1 is a perfectly separated clusters
-1 wrongly seperated clusters
0 - overlapping of the clusters
"""

print('Analysing and interpreting the characteristics of each cluster')
# K-means cluster analysis
print('k-means analysis:')
k_cluster_analysis=df.groupby('k_cluster').mean()
print(k_cluster_analysis)
# Hierarchical analysis
hierarchy_cluster_analysis = df.groupby('hierarchy_cluster').mean()
print('hierarchy_cluster_analysis:')
print(hierarchy_cluster_analysis)
# DBSCAN analysis
cluster_dbscan_analysis = df[df['cluster_dbscan'] !=-1].groupby('cluster_dbscan').mean()
print('cluster_dbscan_analysis:')
print(cluster_dbscan_analysis)

"""Analysis:
K-means: k-means has succesfully divided the dataset into 4 clusters.cluster 0 are frequent fliers,premium customer who are loyal and has huge miles.cluster 1 are customers who have miles based on the shopping or special credit card offers.cluster 2 are customers who were enrolled long ago and now they are inactive.cluster 3 are customers who have newly joined and need time to get rewards.
Hierarchical clustering Analysis:
Total 2 clusters divided into Active and inactive customers
cluster 0 - customers are active and more engaging and got rewards to redeem
cluster 1 - customers are inactive in flying and low miles.
DBSCAN cluster analysis:
Total 2 clusters
cluster 1- customers who have redeemed their awards  in higher quantities that means premium customers
cluster 0 - customers who have  redeemed their awards in low quantity  that means these were less engaging and less flying and low rewards

"""

# Visualizing 11 features from the dataset is not possible so using pca to visualise
from sklearn.decomposition import PCA

# 1. Use our scaled dataframe to perform PCA
pca = PCA(n_components=2)
principal_components = pca.fit_transform(df)

# 2. Create a new dataframe with the 2 principal components
df_pca = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])
df_pca
#3. Add the cluster labels from our cleaned dataframe to this new PCA dataframe
df_pca['kmeans_cluster'] = df['k_cluster']
df_pca['hierarchy_cluster'] = df['hierarchy_cluster']
df_pca['dbscan_cluster'] = df['cluster_dbscan']

print("PCA dataframe with cluster labels is ready:")
print(df_pca.head())

# Visualizing all the results from each clustering algorithm
plt.figure(figsize=(12, 8))
sns.scatterplot(x='PC1', y='PC2', hue='kmeans_cluster', data=df_pca, palette='viridis', s=50)
plt.title('K-Means Clustering Results')
plt.show()

plt.figure(figsize=(12, 8))
sns.scatterplot(x='PC1', y='PC2', hue='hierarchy_cluster', data=df_pca, palette='viridis', s=50)
plt.title('Hierarchical Clustering Results')
plt.show()

plt.figure(figsize=(12, 8))
sns.scatterplot(x='PC1', y='PC2', hue='dbscan_cluster', data=df_pca, palette='viridis', s=50)
plt.title('DBSCAN Clustering Results (Visualized with PCA)')
plt.show()

df.head()

df.head()

#Evaluation and Performance Metrics:

score_kmeans = silhouette_score(df,k_cluster)
print(f"Final K-Means Silhouette Score: {score_kmeans:.3f}")
score_dbscan = silhouette_score(df[cluster_dbscan != -1], cluster_dbscan[cluster_dbscan != -1])
print(f'For DBSCAN, the silhouette score is {score_dbscan:.3f}')
score_hierarchy = silhouette_score(df, hierarchy_cluster.labels_)
print(f"Final Hierarchical Silhouette Score: {score_hierarchy:.3f}")

"""Hierarchical clustering has done a little better job of seperating the clusters when compared with other clustering algorithms."""